DEBUG    asyncio:selector_events.py:64 Using selector: EpollSelector
ERROR    src.utils.decorators:decorators.py:19 An unexpected error occurred: runtime error!
Traceback (most recent call last):
  File "/home/runner/work/apis-testing/apis-testing/src/utils/decorators.py", line 15, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apis-testing/apis-testing/tests/unit/utils/test_decorator.py", line 19, in func
    raise RuntimeError("runtime error!")
RuntimeError: runtime error!